FROM php:8.5-rc-fpm-alpine3.22

LABEL Author="PRATCHAYAPOL <pratchayapol.ja@rmuti.ac.th>" version="latest" org.opencontainers.image.authors="pratchayapol.ja@rmuti.ac.th"

# คัดลอกไฟล์โปรเจกต์ไปยังคอนเทนเนอร์
COPY . /var/www/html

# ติดตั้ง dependencies และ extensions
RUN apk update && apk add --no-cache \
    postgresql-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    zip \
    libzip-dev \
    && docker-php-ext-install zip \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql pgsql mysqli \
    && docker-php-ext-configure gd --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && rm -rf /var/cache/apk/*

# เปิดใช้งาน extensions
RUN docker-php-ext-enable pdo_mysql pdo_pgsql mysqli

# ตั้งสิทธิ์ให้กับ /var/www/html
RUN chmod -R 755 /var/www/html

# ตั้งค่า Working Directory
WORKDIR /var/www/html