FROM nginx:1.30.0-alpine3.23-slim

# Install required dependencies for GD extension
RUN apk update && apk add --no-cache \
    libjpeg-turbo-dev \
    libpng-dev


COPY ../src /var/www/html

RUN chmod -R 777 /var/www/html

# Expose ports 80 and 443
EXPOSE 80 443
