FROM nginx:1.29.1-alpine3.22-slim

LABEL Author="PRATCHAYAPOL <pratchayapol.ja@rmuti.ac.th>" version="latest" org.opencontainers.image.authors="pratchayapol.ja@rmuti.ac.th"

# Install required dependencies for GD extension
RUN apk update && apk add --no-cache \
    libjpeg-turbo-dev \
    libpng-dev


COPY ../src /var/www/html

RUN chmod -R 777 /var/www/html

# Expose ports 80 and 443
EXPOSE 80 443
